### ISSUE TITLE
how to set style_img_dir

### ISSUE THREAD

**Issue by greecehalf** [rinongal/StyleGAN-nada#16]
Hello. You said in the readme that we can replace the source class and target class with style_img_dir. But how to do it in practice? Two different img paths assigned to the same option?

**Comment by rinongal** [comment]
When you use the style_img_dir you don't need to specify a source or target class. 

Instead of using textual directions, it replaces the source point with the average CLIP-embedding of images generated with the original generator, and the target point with the average CLIP-embedding of the images in the style_img_dir.

In practice: just use `--style_img_dir` to specify a directory with examples of your desired target style, and the source is automatically taken from your generator.

**Comment by osofirene** [comment]
> When you use the style_img_dir you don't need to specify a source or target class.
> 
> Instead of using textual directions, it replaces the source point with the average CLIP-embedding of images generated with the original generator, and the target point with the average CLIP-embedding of the images in the style_img_dir.
> 
> In practice: just use `--style_img_dir` to specify a directory with examples of your desired target style, and the source is automatically taken from your generator.

Hello, I am not clear that we just add --style_img_dir without removing -- source and --target class?

**Comment by rinongal** [comment]
You can remove them if you want. ``--style_img_dir`` should be overwriting them anyhow.
