### ISSUE TITLE
How to train the ghost car

### ISSUE THREAD

**Issue by jinjiujiujin** [rinongal/StyleGAN-nada#17]
Hello, I am  using the default setting in the notebook to train the ghost car, and I set training iter=800 instead. But I got the result is far from yours in the paper. Can you share your command to train the ghost car?
![image](https://user-images.githubusercontent.com/35415063/132974504-95aa640e-7728-4f3c-b527-19bfb2e8ee44.png)

**Comment by rinongal** [comment]
Hi,

Unfortunately I generated those in Colab and didn't save the argument file. However, I can manage to replicate the image if I enable the improve_shape button (or alternatively if you run things locally - setting the weights of both clip ViT models to 1.0 seems to do the trick).

These are the results I'm getting with the notebook at 450 iterations with 'improve_shape' and the texts "car" -> "ghost car":

![image](https://user-images.githubusercontent.com/19426368/132997125-4c094e56-2d35-4e5d-a991-601f754b5f1d.png)

**Comment by jinjiujiujin** [comment]
I tried to setting the weights of both clip ViT models to 1.0, but I only get the follwing pictures. It is more white than your results.
![86f824a5b122230645be6c0a9ed155b](https://user-images.githubusercontent.com/35415063/133230960-2702d839-0d67-41c1-8673-5a6f47abc200.png)

**Comment by rinongal** [comment]
These seem similar enough that I'm not sure the difference is anything more than just the effects of some minor random initialization differences (I set the seed _after_ I initialize the models, which means a few minor things like the mean latent code computation for truncation happens before the model runs).

If you want to try and fully replicate the conditions of a notebook run with 'improve_shape' you need to run with:

1) Both model weights at 1.0
2) Mixing at 0.9 instead of 0.0
3) auto_layers_k = 10, auto_layer_iters = 1

so the full command would be something like:

```
python train.py --size 512
                --batch 2 
                --n_sample 4 
                --output_dir /path/to/output/dir 
                --lr 0.002 
                --frozen_gen_ckpt /path/to/car_model.pt 
                --iter 601 
                --source_class "car" 
                --target_class "ghost car" 
                --auto_layer_k 10
                --auto_layer_iters 1 
                --auto_layer_batch 8 
                --output_interval 50 
                --clip_models "ViT-B/32" "ViT-B/16" 
                --clip_model_weights 1.0 1.0 
                --mixing 0.9
                --save_interval 150
```

but I'm not sure you'll get anything fundamentally different. I ran the code a few times locally and it seems the variations I'm getting with multiple runs using the same parameters are of the order of the difference between my photo and the one from your last reply.

**Comment by jinjiujiujin** [comment]
I trained with both model weights at 1.0 for several times and to my satisfaction, I got the image I wanted. thank you!
![image](https://user-images.githubusercontent.com/35415063/133437287-2395daf1-b28a-4067-8387-e243c85625d3.png)
