### ISSUE TITLE
colab cpu inference

### ISSUE THREAD

**Issue by AK391** [rinongal/StyleGAN-nada#3]
great work, is it possible to due inference on cpu in colab?

**Comment by rinongal** [comment]
It's mostly a method for training generators, and the training takes an unreasonably long time on CPU.

If you're aiming at something for Gradio, I could maybe provide you with some pre-trained models and those could be used to just run the generation step / edit real images?

**Comment by AK391** [comment]
@rinongal yes that would be great, also sorry if I was not clear did not mean the training part*

**Comment by rinongal** [comment]
Hey AK - I tested training on a CPU and it takes roughly an hour. I feel like this might be too long to be useful for Gradio, but let me know if you think it's good enough with the queue feature and I'll work on setting up something.

On implementing just inference - is there any inversion model you already have set up in Gradio that you know works well on CPU? Even an optimization-based method? If not, I'll try to convert a few to CPU and see if I can get them to run in reasonable time.

**Comment by jackkwok** [comment]
Does Re-Style inversion work with CPU?  I am also looking for a way to do pure CPU inference.

**Comment by rinongal** [comment]
As far as I am aware, there official version of Re-Style (which we clone) does not currently support running on CPU. It shouldn't be impossible to do the conversion though. You're likely going to need to use the native pytorch implementation of StyleGAN2 (rather than the Rosinality version which uses custom CUDA kernels for some of the ops). You can find a native pytorch version, for example, in the StyleCLIP repo. 

You could also have a look at some of AK's spaces on Huggingface and see what he did there. I think the new spaces do run on GPUs, but maybe he has CPU based inversion code for JoJoGAN or GANs 'N Roses.

**Comment by jackkwok** [comment]
@rinongal : thank you so much for your insights.
