### ISSUE TITLE
Could you provided some pretrained models in your paper?

### ISSUE THREAD

**Issue by kasim0226** [rinongal/StyleGAN-nada#44]
Could you provide these pre-trained models in the following pictire?
Looking forward to your reply.

![擷取](https://user-images.githubusercontent.com/5126656/163139755-08286d98-c63d-4e37-86d6-3f0ccad302a6.PNG)

**Comment by rinongal** [comment]
These are a bit tricky to release since they were trained on some proprietary images and I'm not sure about the legalities involved. I'll ask but it might take some time. If you just want to use them on your own images, our [replicate](https://replicate.ai/rinongal/stylegan-nada) version has them set up.

**Comment by kasim0226** [comment]
Thank you for your reply.

1. Could I knoe how you train those results?
Is it something likes this? (only change target_class)

python train.py --size 1024 
                --batch 2 
                --n_sample 4 
                --output_dir /path/to/output/dir 
                --lr 0.002 
                --frozen_gen_ckpt /path/to/stylegan2-ffhq-config-f.pt 
                --iter 301 
                --source_class "photo" 
                --target_class "shrek" 
                --auto_layer_k 18
                --auto_layer_iters 1 
                --auto_layer_batch 8 
                --output_interval 50 
                --clip_models "ViT-B/32" "ViT-B/16" 
                --clip_model_weights 1.0 1.0 
                --mixing 0.0
                --save_interval 150

2. what is diiferent between 'image' in red and 'text' in red in the following figure?
![image](https://user-images.githubusercontent.com/5126656/163509921-a227d990-ebee-4465-be6f-d45e0bc1bf53.png)

3. You used ffhq pretrained Restyle instead of training it for each face domain, am I right?

**Comment by rinongal** [comment]
The examples under the image block used a target image (i.e. using the `--style_img_dir /path/to/img/dir` option. I can't supply the images since they were shamelessly taken from the internet and I do not own the rights. The images under the text block used zero-shot text targeting. 

Differences between your command and what we used for the image-based examples are just in the number of training iterations (and the need for style image targets):
Shrek: `--iter 601`
Witcher: `--iter 401`
Joker: `--iter 601`
Thanos `--iter 601`

For the text target ones - those should be available in our drive, and the parameters for most of them are in our paper's supplementary, If you want one that isn't in the drive / want me to look up the specific commands to train them, let me know and I'll have a look.

**Comment by rinongal** [comment]
Regarding ReStyle - yes, we used the pre-trained FFHQ versions. ReStyle-e4e (and e4e itself) typically have better results than the pSp variants. You can also have a look at HyperStyle which works with NADA models as well.

**Comment by kasim0226** [comment]
Thank you for your detailed reply.
