### ISSUE TITLE
how to control the performance of new domain

### ISSUE THREAD

**Issue by Johnson-yue** [rinongal/StyleGAN-nada#9]
thank you for your sharing,  it is a good idea for using CLIP model as supervise information and train G

as your paper said, it can generate unseen domain, like "Pig", "Super Saiyan", or "Nicolas Cage".

I think it means only the G not seen those domain dataset , but CLIP know thems.  So it can supervise G to generate them。

I have two question：
1） How to improve the generation effect  for “Pig”， or “Super Saiyan”， （except laten - Mapper） by using “Pig” images？
2） How to generate new domain which CLIP also never seen， like some Medical image， but I have some of them？

**Comment by Johnson-yue** [comment]
about Question-2 :

1) fine-tune an existing model with StyleGAN-ADA  can not performance as
![image](https://user-images.githubusercontent.com/10268274/129999780-f723fd69-ea9b-45c5-94c0-5a5ff0d6742f.png)
the fine-tune result only be similar to _Nicolas Cage Face_  not contain _Dog_ detail

2) I only tens of images :)

Question-3:
if using tens of images and new text  fine-tune CLIP  model, and then train G,  it is possible ?

**Comment by rinongal** [comment]
Hey,

Question 2:
1) Did you use the StyleGAN-ADA dog model to start with, or the face one? The image you pasted uses exactly the StyleGAN-ADA dog model (same one that gets downloaded when you chose dog model in the colab notebook) and the source and target texts outlined below this image ('Dog' to 'Nicolas Cage').
You need to start with a generator that is reasonably similar to what you're trying to reach. You won't be able to convert a face model to snowy mountains, or a church model to a cat.

2) Few shot training with tens of images is going to have the same limit of needing a similar source domain. You can either try looking for a StyleGAN model with visually similar outputs (or at least a similar structure - i.e. a GAN that generates maps may be close enough to medical scans that show lots of veins). You can try doing it with the method I linked at the end of the last question.

Question 3:
Yes, it's absolutely possible and it's something we're working on investigating. It's not entirely trivial though since you need to somehow train the discriminator to 'catch up'. The most naïve idea on this end is to just use the clip-tuned model to generate a lot of samples, fine-tune both the initial generator and the discriminator on this generated data, and then continue to fine-tuning on your small set using a few-shot method.

**Comment by Johnson-yue** [comment]
thanks a lot，I will try it
